version: '3.7'

services:
  cypress:
    build: .
    container_name: cypress-tests
    volumes:
      - .:/app
    environment:
      - CYPRESS_baseUrl=http://your-app-host:3000
    command: npx cypress run
