name: Cypress Docker Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node18.12.0-chrome107

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run cy:run

      - name: Upload screenshots and reports
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Artifacts
          path: |
            cypress/screenshots
            cypress/reports
